[package]
name = "hash_sign"
version = "1.0.0"
authors = []

[addresses]
metaschool = "Replace_with_your_wallet_address_ðŸ”‘"
std = "0x1"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
